### PR TITLE
Mongodb 3 compatibility, variable authdb and arbiter status fixes

### PR DESCRIPTION
**Pull request by warrenpnz**
This pull request includes changes to:
1.  allow for a variable authdb instead of just admin
2. Better determination if a node is an Arbiter and return relevant status
3. Remove mongo_version parameter and determine version from the connection
4. Misc Mongo 3 compatibility fixes for index_miss_ratio, global lock and flushing

### CODE REVIEW

**Comment by mzupan** [comment]
@warrenpnz anyway to rebase this.. also on a side note.. are you open if we create a org for the plugin and you could be a dev of that org.. I don't use mongo much in prod so its hard to keep updated with this project

**Comment by warrenpnz** [comment]
Superseded by PR 200

**Comment by mzupan** [comment]
@warrenpnz do you want me to create a org for the project and add you to the org or are you fine sending PRs?

**Comment by warrenpnz** [comment]
Fine just sending PRs as not sure how much time I'll have available. Truth be told the module does all that I need it to do at the moment and unless Mongodb do a major API or function release, it does not really need a full rewrite, just a cleanup of what's there.
Next stage will be putting in the changes I have in another branch to do version and engine specific memory reporting and also revisit the replication stats.

**Comment by mzupan** [comment]
@warrenpnz ok great.. well thanks for the work getting it up to shape for 3.0

**Pull request closed without merging**
